### ISSUE TITLE
User Story: Navbar

### ISSUE THREAD

**Issue by ErfanNajimi** [ErfanNajimi/sep-2024-hackathon-team-2#3]
As a **user** I can **click on navigation links** so that I can **easily navigate the website** and find new webpages.

### Acceptance Criteria:

- Navbar should be accessible on all pages
- Relevant links should be viewable (for example only show register to new users and logout to logged in users)
- Design should be consistent with the rest of website

### Tasks:

- [ ] Use Bootstrap to create navbar structure

- [ ] Stylise with custom css

- [ ] Include logo as link to home page

- [ ] Backend: using DTL to ensure correct links are shown depending on if user is logged in or out
